import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            Choose a path and edit the code to see more!
          </div>
        </div>

        <div className={styles.center}>
        <Link className={inter.className} href={`/sdk_example`}>Alchemy SDK NFT Example <span>-&gt;</span></Link>
        <Link className={inter.className} href={`/api_example`}>Alchemy API NFT Example <span>-&gt;</span></Link>
        <Link className={inter.className} href={`/connectwallet`}>Alchemy SDK + Connect Wallet <span>-&gt;</span></Link>
        </div>

        <div className={styles.grid}>
          <a
            href="https://buidlnow.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              BuidlNow <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Explore more templates on BuidlNow.
            </p>
          </a>

          <a
            href="https://buidlnow.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn more about this template and how to work with it
            </p>
          </a>

          <a
            href="https://buidlnow.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Explore templates directly on github
            </p>
          </a>
          <a
            href="https://docs.alchemy.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Alchemy Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Explore Alchemy Documentation
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
